apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-config
  namespace: netbird
data:
  config.yaml: |
    issuer: http://3.108.237.19:30556

    storage:
      type: memory

    web:
      http: 0.0.0.0:5556

    staticClients:
      - id: netbird
        name: NetBird
        secret: secret
        redirectURIs:
          - http://3.108.237.19:30080/*

    enablePasswordDB: true

    staticPasswords:
      - email: admin@netbird.local
        username: admin
        userID: "1"
        hash: "$2y$12$KIXQqv3ZcQh9Qm1vQq3o7eOq6G1Y9s0n9g0JQhG3m8q7c0qv1n5e"
